### ISSUE TITLE
Why stop this good job? 

### ISSUE THREAD

**Issue by ginus** [Satyam/mithril-isomorphic#1]
I have read you code after I try miso and mithril-node-render. it real nice job, why stop?

**Comment by Satyam** [comment]
This was a 'proof of concept' because @lhorie kept insisting it couldn't be done so I meant to show it could.   

The problem with actually turning it into a product is that Mithril has no 'protected' API to allow for accessing certain internal features as this code requires. That is the reason why I have a modified version of Mithril in this repository, which would need to be maintained in parallel with any release of Mithril itself. If there were a 'protected' API, then this could be a product, otherwise, there is no way to maintain it.

Leo said he would look into this, but hasn't done so, as far as I know.  Nobody else seemed to care about making Mithril isomorphic either so it understandably fell  down on Leo's priority list.  In a recent thread  for a Mithril 2.0 wishlist nobody mentioned isomorphism.  

I haven't written a line of code for the last two months, that doesn't mean I don't keep banging the keys on my laptop, I finally wrote a [science fiction novel](https://leanpub.com/thegodsthatwerent) that I had in my mind for a long time. It was more rewarding than being the only guy to care about isomorphism.

**Comment by ginus** [comment]
Thanks, wish your novel would be born soon:)

**Comment by Satyam** [comment]
It is already [published](https://leanpub.com/thegodsthatwerent), but thanks for your good wishes anyway. 

Just closing this issue.
